logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

#RootCAs = [ "/mycert.cert" ]
InsecureSkipVerify = false

[web]
address = ":8080"

# [web]
# address = ":8443"
# ReadOnly = false
# CertFile = "ssl/wildcard.example.com.crt"
# KeyFile = "ssl/wildcard.example.com.key"
#   [web.auth.basic]
#   usersFile = ".htpasswd"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "ssl/wildcard.api.example.com.crt"
      KeyFile = "ssl/wildcard.api.example.com.key"
      [[entryPoints.https.tls.certificates]]
      CertFile = "ssl/wildcard.example.com.crt"
      KeyFile = "ssl/wildcard.example.com.key"

[consulCatalog]
endpoint = "127.0.0.1:8500"
domain = "example.com"
prefix = "traefik"
constraints = ["tag==kubernetes"]
